### ISSUE TITLE
Syntax Error Preventing Inspection

### ISSUE THREAD

**Issue by mbitson** [xlucas/ssl-inspector#2]
Hey There,

I'm trying to run the following command to test a site's support of TLS v1.2:
`ssl-inspector -h www.example.com -p 443 -s TLSv1.2 -k DHE -e DSS -b 256`

(I did change example.com to the site I wanted to test but changed it back for this Issue)

I am running the following software:
- Vagrant Machine using Puppet
- VM is on Ubuntu 14.04
- Mac Book Pro using Sierra
- VM is running Ruby v2.1.1 (Change to this specifically to attempt this command, used rvm install 2.1.1)

I get the following output each time:

```
/usr/local/bin/ssl-inspector: line 1: --2016-10-27: command not found
/usr/local/bin/ssl-inspector: line 2: syntax error near unexpected token `('
/usr/local/bin/ssl-inspector: line 2: `Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.44.133'
```

Any ideas? Any information you could use from me to help aid in fixing this?

Thank you!

**Comment by xlucas** [comment]
Hello sounds like `/usr/local/bin/ssl-inspector` isn't the expected script content but some output from your download command instead.

**Comment by mbitson** [comment]
Herp, thank you!!
